### ISSUE TITLE
Godzilla: Save the earth - 

### ISSUE THREAD

**Issue by AnsgarTOdinson** [xemu-project/xemu#1463] opened 2023-06-20 15:12 UTC
### Bug Description

Strange lighting glitches appear on uneven ground.  Specifically, if there is lighting such as fire breath or a powerup that is rendered on a hill, translucent polygons appear on the lower ground levels.

A second issue is that the game slows down and sometimes crashes when there are lots of particle effects on screen. 

### Expected Behavior

There should be no strange polygons and the game should not slow or crash

### xemu Version

0.7.96

**Comment by mborgerson** [comment] 2023-06-20 23:55
Sounds like a duplicate of #1210

In the future you can check for reported issues on the compatibility tracker page for the title

**Closed as completed by mborgerson** 2023-06-20 23:55 UTC
Labels: bug
