### ISSUE TITLE
Halo 2 v1.0: Assertion Failed! Line 5986

### ISSUE THREAD

**Issue by leewickert** [xemu-project/xemu#759] opened 2022-03-06 22:01 UTC
### Title

Halo 2 v1.0: Assertion Failed! Line 5986

### Bug Description

This error only appears to occur during multiplayer campaign, introduction cut scene plays, as soon as the actual level begins, both players appear and you see the split screen, no error yet. However, the pictured error occurs when both players are simultaneously entering in commands. 

For instance - when the introduction cut scene ends, if no player is making any inputs, the error will not occur. If only player 1 enters inputs, still no error. If player 1 stops, and player 2 starts entering inputs, still no error. However, if both player 1 and 2 enter inputs at the same time the error occurs immediately and the game closes out.

![20220306_145737_resized_20220306-150213](https://user-images.githubusercontent.com/64300062/156943737-a17d258c-f7aa-408b-8cff-6a7b1c049fc8.jpg)
 

### Expected Behavior

When playing co-operative campaign missions, both players should be able to input commands simultaneously without error. 

### xemu Version

0.6.2-79-ga32f271d55

### System Information

OS: Windows 11
CPU: AMD Ryzen 5 5600X 6-Core Processor 4.20 GHz
GPU: NVIDIA GeForce RTX 3070
GPU Driver NVIDIA 27.21.14.6140

### Additional Context

New to the community! Let me know what other information is necessary from me! Thanks.

**Comment by dracc** [comment] 2022-03-06 22:07
Duplicate of #420 .

**Closed as completed** 2022-04-25 05:13 UTC
Labels: bug
