### ISSUE TITLE
Terminator Redemption Shadows Bug

### ISSUE THREAD

**Issue by orderorder** [xemu-project/xemu#1044] opened 2022-06-08 21:37 UTC
### Title

https://xemu.app/titles/4947003e/#Terminator-3-The-Redemption

### Bug Description

![Captura desde 2022-06-08 23-23-10](https://user-images.githubusercontent.com/7293829/172720661-390e8085-214e-42fe-9da5-c8be4d9851dd.png)

### Expected Behavior

shadows should display correctly

### xemu Version

0.7.29

### System Information

Manjaro Linux Release 21.2.6

AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G

mesa-22.0.4-1

Same problem with Windows 10 and Nvidia 3070M

### Additional Context

Anyway the game freezes in that scene at the beginning of the game

**Comment by Ernegien** [comment] 2022-06-08 21:42
Duplicate of https://github.com/mborgerson/xemu/issues/577

**Comment by Triticum0** [comment] 2022-06-08 21:50
Actually a dupe of #1028 I properly rename the issue

**Comment by Triticum0** [comment] 2022-07-25 14:44
This also affects Doom 3 
![xemu-2022-07-25-15-24-05](https://user-images.githubusercontent.com/71127352/180801688-77968a34-a6de-44bc-aaf6-6103e5518b42.png)

**Closed as completed** 2023-05-01 20:58 UTC
Labels: bug
