### ISSUE TITLE
Conker Live and Reloaded - Assertion Failed

### ISSUE THREAD

**Issue by Nino-Z** [xemu-project/xemu#424] opened 2021-07-23 11:05 UTC
### Bug Description

https://xemu.app/titles/4d530051/#Conker-Live-Reloaded (Duplicate of #423)

Conker has been crashing many times at random during my playthrough, however I have now reached a point at which is crashes consistently. It's when you are about to face the giant poo boss - during the cutscene when the dung beetle tells you to run. 

I have tried two different games in order to make sure it isn't the game itself and the crash happens every time regardless.

Message:
microsoft visual c++ runtime library
assertion failed
program ...
file ...
expression (index_count*vertex_size) ==
(pg->inline_array_length*4)
for information on how your program can cause an
assertion failure, see the visual c++ documentation on asserts

### Expected Behavior

Should not crash at all

### xemu Version

Version: 0.5.4-39-gedf3735718
Branch: master
Commit: edf3735...
Date: Tue Jul 20 17:39:54 UTC 2021

### System Information

OS: Windows 10 (64bit)
CPU: i7 7700k @ 4.20 GHz
GPU: Zotac GTX 1080 Amp Extreme!
Driver: 471.11

### Additional Context

None

**Comment by Nino-Z** [comment] 2021-07-24 13:48
Here are some additional crashes I have recorded:
![After the furnace fight you come out and run from the bulldog fish - crashes can occur several times during this section](https://user-images.githubusercontent.com/23583100/126870426-2b80eac9-bee7-441e-8eec-9846aa82a667.jpg)
- After the furnace fight you come out and run from the bulldog fish - crashes can occur several times during this section

![During the mighty poo fight at the end when moving towards the flusher](https://user-images.githubusercontent.com/23583100/126870660-b9b65600-4d5d-402c-8722-7b6601207e32.png)
- During the mighty poo fight at the end when moving towards the flusher. 

![After the mighty poo fight](https://user-images.githubusercontent.com/23583100/126870440-95889b25-d5da-42a6-89a6-9e8cf6b325d5.png)
- After the fight you need to descend into the hole where the poo got flushed - multiple crashes here. Seems like the poo boss room is prone to crashing a lot!

![Night Club after second boulder is on button](https://user-images.githubusercontent.com/23583100/126870475-5f60a308-e6f6-4798-9d7b-40b75d8d5bfa.jpg)
- Later on in the boulder night club you need to solve a puzzle by pushing boulders onto pressure plates. After pushing the second boulder on the second pressure plate, several crashes occur.

![Conker's Girlfriend Cinematic where she gets Abducted](https://user-images.githubusercontent.com/23583100/126870498-e4b59ace-7d56-4c80-93fa-476fcdbe47ac.png)
- During the cutscene, where Conker's girlfriend "Berri" is abducted - multiple crashes, including after the cutscene fades to black.

![After the military pitch video](https://user-images.githubusercontent.com/23583100/126870542-49efd4e5-25b0-4c02-b5b3-47c0aa6d96f0.jpg)
- After the cutscene with the announcement of the war and the call to arms by the military, a crash occurs as you enter the zone. 

There were more, but I didn't take pictures. When rolling the dung ball, a crash may occur on rare occasions if you are looking towards the "dung cabin". Others exist as well, but these should be a good start, since they are the most pressing ones.

**Comment by belegdol** [comment] 2021-08-08 17:26
Happens with 0.6.0 on Linux too:
```
xemu: ../hw/xbox/nv2a/pgraph.c:6291: pgraph_bind_inline_array: Assertion `(index_count*vertex_size) == (pg->inline_array_length*4)' failed.
```

**Comment by EdLeonhart** [comment] 2021-08-31 15:22
I would like to add that i managed to complete the whole story of the game yesterday on a Window 10 Machine, by simply pressing the ignore button on the assertion errors. The areas i found was having the hardest time is as mentioned the GMP and Bullfish, where the errors are frequent and many at once, however simply spam clicking ignore will eventually let you continue on.
Therefore i'll say that the game is fully playable, with only minor issues for now, as you can play it through from start to end.

**Comment by Saradey** [comment] 2021-09-01 00:37
mac os, you can't ignore it, there's just a crash

**Comment by EdLeonhart** [comment] 2021-09-01 01:15
You're saying you do not have to the option to click ignore whenever an assertion error occurs? I want to point out that as stated in the documentation, they're just error occuring due to a feature not being implemented yet.
Game runs from start to end on a Windows 10 machine, with a rather small amount of Assertion errors at certain parts, i can't test it on other OS types.

**Comment by Saradey** [comment] 2021-09-01 23:48
when this error occurs, a crash occurs

**Comment by Saradey** [comment] 2021-09-01 23:49
да, когда возникает эта ошибка происходит краш

**Comment by Saradey** [comment] 2021-09-01 23:49
yes, when this error occurs, a crash occurs

**Comment by EdLeonhart** [comment] 2021-09-05 02:14
Are you able to share a picture of what the "Crash" look likes on a Mac? As shown in Nino-Z's pictures above, whenever an assertion error occurs, you should have the options of "Abort", "Retry" and "Ignore", and what i've repeated since my first post, i was able to play AND finish the whole game, by simply pressing the "Ignore" option whenever an assertion error appeared.

**Comment by Saradey** [comment] 2021-09-06 21:00
Crash and show this window
![alt text](https://c.radikal.ru/c01/2109/78/2638a811f61d.png)

**Comment by Nino-Z** [comment] 2021-09-06 21:12
I am a bit disappointed that these issues have not been fixed yet.

**Comment by mborgerson** [comment] 2021-09-06 21:45
The issue is known and will be fixed. Please remember this project is developed voluntarily, for fun, and provided at zero cost to you; then manage your expectations accordingly. Locking the issue for now.

**Closed as completed** 2022-05-28 22:08 UTC
Labels: bug
