### ISSUE TITLE
Halo 2: invisible floor/ground

### ISSUE THREAD

**Issue by OddAshyt** [xemu-project/xemu#737] opened 2022-02-17 04:18 UTC
### Title

https://xemu.app/titles/4d530064/#Halo-2

Halo 2 v1.0

### Bug Description

Invisible Floor/ground

Steps to reproduce  this issue
1. Launch the game
2. Select campaign
3. Play the campaign for a few minutes
![1](https://user-images.githubusercontent.com/97839897/154403728-739cc314-7d44-4845-98df-bbb1b05185c6.PNG)

The above screenshot if from the 1st mission which is to get used to controls and walk around

### Expected Behavior

When playing campaign sometimes floors and ground are expected to be invisible
![1](https://user-images.githubusercontent.com/97839897/154403960-430b02c2-b31a-4754-a38c-2f1547e4a8a7.PNG)
![2](https://user-images.githubusercontent.com/97839897/154403966-ce4dd273-d3e2-4e50-b4f2-4822e81e8b31.PNG)
![3](https://user-images.githubusercontent.com/97839897/154403972-b2f82193-c849-49f7-acad-33344d0f1c0c.PNG)

### xemu Version

0.6.2-75-g8919bae311

### System Information

OS: Windows 10
CPU: AMD Ryzen 5 3500X
GPU: GTX 1650
GPU driver:  NVIDIA Game Ready driver Version 511.79

**Comment by Alastair0100** [comment] 2022-02-20 16:38
possible duplicate https://github.com/mborgerson/xemu/issues/55

**Comment by OddAshyt** [comment] 2022-02-24 03:59
> possible duplicate #55

I saw the bug report and I see a .log file posted by one of the contributor's, is the .log file a fix? and if it is how do I fix this?

**Comment by abaire** [comment] 2022-06-04 04:17
This is indeed a duplicate of #55 and should be closed.

**Comment by Shoegzer** [comment] 2022-06-09 17:49
@OddAshyt Please close this.  There is no fix yet, please be patient.

**Closed as completed** 2022-06-09 20:23 UTC
Labels: bug
