### ISSUE TITLE
No Controller mapping. Unplayable 

### ISSUE THREAD

**Issue by EarthsDefect** [xemu-project/xemu#1552] opened 2023-11-02 10:06 UTC
### Bug Description

Left is up, up is left, right is down, down is right. 

If I cant remap makes games unplayable.... Needs to be fixed asap

### Expected Behavior

should just have mapping option

### xemu Version

whatever is newest.

**Comment by antangelo** [comment] 2023-11-02 12:30
Duplicate of #136

**Closed as not planned by antangelo** 2023-11-02 12:30 UTC
Labels: bug
