### ISSUE TITLE
https://xemu.app/titles/4156000f/

### ISSUE THREAD

**Issue by Deadliestbridge** [xemu-project/xemu#1076] opened 2022-06-18 18:14 UTC
### Title

Obi-Wan Crash related to audio issues

### Bug Description

when loaded on default emulator settings game will crash when loading the second level (ERROR:../hw/xbox/mcpx/apu.c:1904:voice_get_samples: assertion failed: (segment_offset != 0)
Bail out! ERROR:../hw/xbox/mcpx/apu.c:1904:voice_get_samples: assertion failed: (segment_offset != 0)

but with the experimental real time DSP the issue is not present but causes significant audio distortion 

### Expected Behavior

Not Crashing

### xemu Version

7.40

### System Information

OS: Windows 10
CPU: Ryzen 5800x
GPU: 3080 Driver 516.40

**Comment by Deadliestbridge** [comment] 2022-06-18 18:19
it also fixed the loading screens for some reason I blame black magic

**Comment by Triticum0** [comment] 2022-06-21 21:44
dupe of #380

**Closed as not planned** 2023-10-16 21:12 UTC
Labels: bug
