### ISSUE TITLE
pgraph_render_display_pvideo_overlay: Assertion in_pitch >= in_width * 2' failed.

### ISSUE THREAD

**Issue by doinkers** [xemu-project/xemu#947] opened 2022-05-21 00:03 UTC
### Title

https://xemu.app/titles/4d53005f/
MS-095

https://xemu.app/titles/54540004/
TT-004

### Bug Description
Known games with this issue:
- Voodoo Vince
- Serious Sam
- Other unknown games that use pvideo to display intro videos

The above games cause an assertion failure if you attempt to load an ISO while the game intro videos are playing.

Reproduction:
1: Load game and close Xemu so it runs it by default on next boot
2: Open Xemu, and wait until the game's intro videos are playing
3: Load Disc (It can be any ISO, even the same game)
4: Assertion failed.
`xemu: ../hw/xbox/nv2a/pgraph.c:4897: pgraph_render_display_pvideo_overlay: Assertion in_pitch >= in_width * 2' failed.`

Reproduction Alternative:
1: Load game and close Xemu so it runs by default on next boot
2: Open Xemu and Eject disk when the game's intro videos are playing
3: Assertion failed.

Reproduction video on Voodoo Vince:

https://user-images.githubusercontent.com/105917902/169626030-474f3638-8323-4b2b-ab58-f0518077f34d.mp4

### Expected Behavior

For the assertion not to fail.

### xemu Version

Version:      0.7.17
Branch:       master
Commit:       66b57dca9c5c461c13cd44f977bd357677200be3
Date:         Fri May 20 01:10:05 UTC 2022

### System Information

CPU:          Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: ATI Technologies Inc.
GPU Model:    AMD Radeon RX 5600 XT
Driver:       4.0.14800 Core Profile Context 22.4.2 30.0.15021.7000
Shader:       4.60

### Additional Context

Cheers to Hadet in the Discord for helping \:)

**Comment by HadetTheUndying** [comment] 2022-05-21 00:08
I went ahead and confirmed this bug in Discord. Here is a backtrace for what's happening

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff649b536 in __GI_abort () at abort.c:79
#2  0x00007ffff649b41f in __assert_fail_base (
    fmt=0x7ffff6603ea8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x5555560bf6f7 "in_pitch >= in_width * 2", 
    file=0x5555560bf560 "../hw/xbox/nv2a/pgraph.c", line=4897, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff64aa792 in __GI___assert_fail (
    assertion=assertion@entry=0x5555560bf6f7 "in_pitch >= in_width * 2", 
    file=file@entry=0x5555560bf560 "../hw/xbox/nv2a/pgraph.c", line=line@entry=4897, 
    function=function@entry=0x5555560bdca0 <__PRETTY_FUNCTION__.2> "pgraph_render_display_pvideo_overlay") at assert.c:101
#4  0x0000555555a8b130 in pgraph_render_display_pvideo_overlay (d=d@entry=0x7fff794cb010)
    at ../hw/xbox/nv2a/pgraph.c:4897
#5  0x0000555555a8b3b2 in pgraph_render_display (d=d@entry=0x7fff794cb010, 
    surface=surface@entry=0x7ffec520e940) at ../hw/xbox/nv2a/pgraph.c:5016
#6  0x0000555555a92d3b in pgraph_gl_sync (d=d@entry=0x7fff794cb010)
    at ../hw/xbox/nv2a/pgraph.c:5053
#7  0x0000555555a82694 in process_requests (d=d@entry=0x7fff794cb010)
    at ../hw/xbox/nv2a/pfifo.c:465
#8  0x0000555555a8349d in pfifo_thread (arg=arg@entry=0x7fff794cb010)
    at ../hw/xbox/nv2a/pfifo.c:486
#9  0x0000555555c48bb5 in qemu_thread_start (args=0x7fff8019ce80)
    at ../util/qemu-thread-posix.c:541
#10 0x00007ffff6645eae in start_thread (arg=0x7ffeeebf6640) at pthread_create.c:463
#11 0x00007ffff65732ff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

System Info:
```
CPU:          AMD Ryzen 7 2700X Eight-Core Processor         
OS Platform:  Linux
OS Version:   Void Linux
Manufacturer: AMD
GPU Model:    AMD Radeon RX Vega (VEGA10, DRM 3.44.0, 5.16.20_1, LLVM 12.0.1)
Driver:       4.6 (Core Profile) Mesa 21.3.7
Shader:       4.60
```

xemu info:

```
Version:      0.7.17
Branch:       master
Commit:       66b57dca9c5c461c13cd44f977bd357677200be3
Date:         Sat May 21 12:01:53 AM UTC 2022
```

**Comment by Triticum0** [comment] 2022-05-26 22:10
dupe of #330, also this affects all intro in the library.

**Comment by doinkers** [comment] 2022-05-26 23:15
> 

Huh, so it is. I did try to search for it but I didn't see anything. Closing. @HadetTheUndying want to paste your backtrace as a comment in #330 ?

**Comment by doinkers** [comment] 2022-05-26 23:19
Actually, reopening. After reading through #330 it seems like this issue is similar but not exactly the same. Voodoo Vince and Serious Sam do not crash during, or after the FMV intros. They only crash when you eject the disk.

**Comment by Triticum0** [comment] 2022-05-27 00:28
That's fine, but test any intro for any game that is not Voodoo Vince and Serious Sam there will all have the same issue. It more of a general issue tbh.

**Comment by mborgerson** [comment] 2022-05-27 00:39
It's a duplicate, not game specific. I'll close in favor of #330

**Closed as duplicate by mborgerson** 2022-05-27 00:39 UTC
Labels: bug
