### ISSUE TITLE
Xemu crashing on the main menu

### ISSUE THREAD

**Issue by Gareth17andMinnie14** [xemu-project/xemu#1462] opened 2023-06-20 12:51 UTC
### Bug Description

![Issue for xemu](https://github.com/xemu-project/xemu/assets/122693175/10fdd9c6-48e5-4ab3-82f6-59d5d1170404)

I just discovered this today with Xemu and it seems like it has some sort of malfuction when you wait for a few minutes you get this message pop up saying "Assertion failed!" and whenever you choose retry it crashes the entire emulation, but however that's not all if you ignore it the emulation of Xemu does not crash and continues to play as normal, so I hope this issue can be looked into and sorted out cause this seems like a problem here......

### Expected Behavior

Xemu crashes only if you wait a couple of minutes if you aren't doing anything on the main dashboard of the xemu emulator and can give you the choice to retry or abort, but when you click ignore it just let's you continue using the emulator

### xemu Version

Version:      0.7.96
Branch:       master
Commit:       0ee7502c23b3c7c964c5295ff283284bfc1526d2
Date:         Sun Jun 18 08:01:30 UTC 2023

### System Information

CPU:          Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver:       4.0.0 NVIDIA 536.23
Shader:       4.00 NVIDIA via Cg compiler

**Comment by antangelo** [comment] 2023-06-20 12:56
Duplicate of #310

**Closed as completed** 2023-06-20 23:53 UTC
Labels: bug
