### ISSUE TITLE
Adding the support of memory card usage

### ISSUE THREAD

**Issue by VladimirVSC** [xemu-project/xemu#1295] opened 2022-11-21 11:22 UTC
### Feature Request

It is much more comfortable to keep Xbox save files on a memory card of small capacity instead of using 8 Gb Hdd, forcefully stuffed with a pile of unnecessary game files. Besides, using of memory card is a native Xbox feature, so please don't ignore it.

**Comment by mborgerson** [comment] 2022-11-21 13:47
You can attach XMUs using the monitor. See website for docs

Duplicate of #1128 #389

**Closed as completed by mborgerson** 2022-11-21 13:47 UTC
Labels: enhancement
