### ISSUE TITLE
Texture dumps are needed to be able to access them while playing and then be able to remaster the game.

### ISSUE THREAD

**Issue by Josemaster2** [xemu-project/xemu#1801] opened 2024-12-01 22:15 UTC
### Feature Request

Texture dumping is needed as PS2 and Dolphin have, without that you cannot improve the game with remastered textures or remastering with AI and that is when you play the dumping

**Comment by mborgerson** [comment] 2024-12-02 00:32
Duplicate of #1337

**Closed as completed by mborgerson** 2024-12-02 00:32 UTC
Labels: enhancement
