### ISSUE TITLE
Oddworld: Stranger's Wrath "skybox glitch"

### ISSUE THREAD

**Issue by Proxybat** [xemu-project/xemu#1711] opened 2024-07-27 01:13 UTC
### Title

https://xemu.app/titles/4541006d/#Oddworld-Stranger-s-Wrath

### Bug Description

Skybox glitches out and repeats/copies whatever's in front of the skybox: walls, game ui, enemies, etc. This is an annoying bug as it makes first person view harder to play, especially while you're in the bushes.

Steps to recreate this issue:
1. Launch game.
2. Go somewhere where the skybox should be visible.
3. Move the camera around to see bug in action.

Video attached is an example of the bug in action. **Strobe & epilepsy warning:**

https://github.com/user-attachments/assets/fa1b2839-513e-404d-95cd-ac7e111bd313

### Expected Behavior

Expected behavior:
When viewing the skybox the skybox should render normally, and only display the skybox. Not repeat anything that's in front of it.

### xemu Version

Version:      0.7.131
Branch:       master
Commit:       a8d8ef5484686ab53e67ae10363747eec7eb6729
Date:         Tue Jul 23 06:54:54 UTC 2024

### System Information

OS: Windows 11 Version 23H2 64bit
CPU:  11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
GPU:  NVIDIA GeForce RTX 3070 Laptop GPU
Driver Version: 4.0.0 NVIDIA 560.70

**Comment by Triticum0** [comment] 2024-07-27 08:46
Dupe of #1211

**Comment by mborgerson** [comment] 2024-07-29 19:27
Closed as duplicate

**Closed as not planned by mborgerson** 2024-07-29 19:27 UTC
Labels: bug
