### ISSUE TITLE
Star Wars Obi-Wan Music did Not play

### ISSUE THREAD

**Issue by Deadliestbridge** [xemu-project/xemu#855] opened 2022-04-26 01:42 UTC
### Title

https://xemu.app/titles/4156000f/#Star-Wars-Obi-Wan

### Bug Description

Music has been silenced in the newest update 

### Expected Behavior

music during the menu and gameplay plays

### xemu Version

Version: 0.6.3-1-g8125e1302f
last working was 6.2

### System Information

Windows 10
Nvidea driver 512.15 
3080 10gb 
Ryzen 3600
16gb DDR4

**Comment by abaire** [comment] 2022-04-26 22:41
@Deadliestbridge can you edit the title of this bug so it's immediately clear what the problem is without having to open it?

Something like "Star Wars Obi-Wan: Music does not play" would probably be enough

**Comment by Triticum0** [comment] 2022-04-29 15:44
This is a duplicate of #566 ignoring the assertion breaks the sound

**Comment by mborgerson** [comment] 2022-04-29 20:58
Please do not file issues for things that happen after ignoring assertions.

**Closed as completed by mborgerson** 2022-04-29 20:58 UTC
Labels: bug
