### ISSUE TITLE
Dead or Alive 3

### ISSUE THREAD

**Issue by legolas119** [xemu-project/xemu#618] opened 2022-01-05 20:42 UTC
### Title

https://xemu.app/titles/4d53002d/#Dead-or-Alive-3

### Bug Description

The game starts correctly, during the opening and into the menu the game works at fullspeed. But after selecting a characters, the match start and the game runs really slowly

### Expected Behavior

The game should work at full speed during the match too

### xemu Version

Latest Release: v0.6.2-21-gd0f241c516
Dec 29, 2021

### System Information

OS: Windows 10
CPU: AMD Ryzen 3700X
GPU: RTX 2060 Super
RAM: 2 x 8 GB Kingston HyperX Predator 3200-16

**Comment by MattPonton** [comment] 2022-01-08 01:36
I believe this is a duplicate of Issue #493

Tested on Xemu Version 0.6.2-22-gedbe932d8c
Released: Thu Jan 6 08:35:46 UTC 2022

**Closed as completed** 2022-03-02 21:04 UTC
Labels: bug
