### ISSUE TITLE
Mouse support, keyboard and profile remapping

### ISSUE THREAD

**Issue by UserGit-2021** [xemu-project/xemu#827] opened 2022-03-23 09:40 UTC
### Feature Request

Do you have any plans to add mouse support, key remapping, and settings profile in the future?

Other emulators support mouse and key remapping:
CXBX-Reloaded
RPCS3
PCSX2
Dolphin

Thanks.

**Comment by mborgerson** [comment] 2022-03-23 10:03
Yes. Duplicate of #136

**Closed as completed by mborgerson** 2022-03-23 10:03 UTC
Labels: enhancement
