### ISSUE TITLE
Suggestion: CHD support for XISO images

### ISSUE THREAD

**Issue by TomTurbine** [xemu-project/xemu#1289] opened 2022-11-07 00:10 UTC
### Feature Request

Just suggesting support for CHD compressed images similar to how Playstation and Sega CD based emulators do.

### Additional Context

While I know that regular Xbox images are huge and doesn't compress well (Really wish ReDump would have XISO dats as well but oh well), just to see, I took an XISO and compressed them with both 7-zip normally and CHDMan to see how they worked and here is the results.

4x4 Evo 2
XISO: 1.26GB
CHD: 620MB

And just to see, I compressed it in 7-zip with a little above ultra settings and got it down to 434MB.

And while CHD doesn't get it down to full 7-zip, having it cut the file size more than in half while still being a playable format is still a huge benefit.

**Comment by Godsbane** [comment] 2022-11-07 00:36
CHD is my favorite format atm, so I would also love to see this.

**Comment by mborgerson** [comment] 2022-11-07 01:56
Duplicate of #238

**Closed as completed by mborgerson** 2022-11-07 01:56 UTC
Labels: enhancement
