### ISSUE TITLE
XEMU “UWP” for XboxDevMode

### ISSUE THREAD

**Issue by BrandiBlitz** [xemu-project/xemu#1377] opened 2023-02-02 00:57 UTC
### Feature Request

Making a UWP version of XEMU for Xbox Dev Mode. Mainly for accessibility and having more ways to play my OG Xbox titles.

### Alternatives

I have considered porting XEMU to RetroArch, but the Dolphine Project (Wii/GC) made their own UWP for XboxDevMode and works far better than being bundled in With RetroArch and being far more user friendly.

### Additional Context

Having XEMU “UWP” on XboxDevMode will not only help with accessibility, but also be able to have Halo LAN multiplayer parties again.

**Comment by mborgerson** [comment] 2023-02-02 01:03
Duplicate of #272 #487. Not planned today, but maybe in the future after compatibility is higher. In the mean time, maybe lobby Microsoft to expand their backwards compatibility if you want to play original Xbox games on modern Xbox.

>  also be able to have Halo LAN multiplayer parties again

You can do this with xemu today, see https://xemu.app/docs/networking/

**Closed as completed by mborgerson** 2023-02-02 01:03 UTC
Labels: enhancement
