### ISSUE TITLE
Not a bad dump. Dead Or Alive 3 (Japanese version) freezes now when pressing start on the title screen

### ISSUE THREAD

**Issue by AkihitoZero5454** [xemu-project/xemu#1397] opened 2023-02-18 03:25 UTC
### Title

https://xemu.app/titles/4d53002d/#Dead-or-Alive-3

MS-045 [4d53002d]

### Bug Description

When mostly I play Dead Or Alive 3 on Xemu it functions well and does fine but now it will freeze when pressing start on the title screen.

### Expected Behavior

Get to the main menu perfectly.

### xemu Version

v0.7.84

### System Information

Windows 10

**Comment by MattPonton** [comment] 2023-05-23 18:24
I never saw this issue, even in v0.7.84.

However, testing in the latest version [v0.7.90], I am also unable to reproduce the issue.

https://github.com/xemu-project/xemu/assets/45347806/8e45daac-6644-4c09-b45a-87cea33df321

**Comment by mborgerson** [comment] 2023-05-23 18:26
@AkihitoZero5454 since @MattPonton confirmed it works I'll close the issue. If you're still having problems, let's compare hashes of game files

**Closed as not planned by mborgerson** 2023-05-23 18:26 UTC
Labels: bug
