### ISSUE TITLE
Group S Challenge (USA) - Assertion failed! (shaders.c) when starting races.

### ISSUE THREAD

**Issue by ehw** [xemu-project/xemu#1410] opened 2023-03-19 18:46 UTC
### Title

https://xemu.app/titles/43430005/#Group-S-Challenge

CC-005 [43430005]

### Bug Description

The game crashes xemu with an "Assertion failed!" message that affects line 509 of shaders.c when starting a race or letting the game go past the title screen.

To recreate, load up the game, press Start, select Arcade Mode, select Time Trial, and keep going through the menus until the game eventually crashes.

### Expected Behavior

The game should not crash when beginning a race.

### xemu Version

Version:      0.7.85
Branch:       master
Commit:       065c74a00fe402f65147e9b0d1a1eeac1b4b609f
Date:         Mon Mar  6 21:06:28 UTC 2023

### System Information

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 531.29
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

![image](https://user-images.githubusercontent.com/885618/226199673-ca0c192e-3050-4d71-9c0c-f391c51fe653.png)

**Comment by Triticum0** [comment] 2023-03-20 18:10
dupe of  #379

**Comment by Triticum0** [comment] 2023-07-10 15:33
The game fixed this can be closed

**Closed as completed** 2023-07-10 18:48 UTC
Labels: bug
