### ISSUE TITLE
Title Name: SSX 3 In Game Error

### ISSUE THREAD

**Issue by FLIPPER4440** [xemu-project/xemu#500] opened 2021-10-18 07:50 UTC
### Title

https://xemu.app/titles/4541003c/#SSX-3

### Bug Description

[https://pasteboard.co/EWjjipo7Tu0A.png](url)

I receive the following error shown in the picture above. If I select ignore, it just works for a sec & then spams the exact same error no matter how many times you click.

Note that many of the intro screens dont display but the game is playable beyond that so thats forgettable.

### Expected Behavior

For game to continue playing well from Conquer The Mountain with Psymon selected, the initial gameplay.

### xemu Version

v0.6.1-20-g21718399f2

### System Information

Windows 10 Pro 64-Bit
Ryzen 3600X
32GB 3200MHz
RTX 2080
1TB Samsung SSD

**Comment by Triticum0** [comment] 2021-11-01 00:38
This bug also affect Gungriffon Allied Strike when using resolution scaling.

**Comment by Triticum0** [comment] 2021-11-20 18:59
@FLIPPER4440 Where you using Resolution scaling when the bug occurred

**Comment by FLIPPER4440** [comment] 2021-11-20 22:23
Yes

**Comment by Triticum0** [comment] 2021-11-20 23:25
That why it crashed #520. I will merge it into #520. You can close the issue or add other issues that occurred with the game with Resolution scaling turned off

**Comment by Triticum0** [comment] 2022-04-30 13:54
Duplicate of #520, Please close Issue.

**Closed as completed** 2022-05-24 09:46 UTC
Labels: bug
