### ISSUE TITLE
hotkeys config

### ISSUE THREAD

**Issue by segamanov** [xemu-project/xemu#1734] opened 2024-08-04 21:35 UTC
### Feature Request

It is necessary to add the ability to reassign the emulator's hotkeys. At least output it to a separate file similar to hotkeys.cfg. In many games, the back + start buttons are an exit to the main menu of the game, while I press this, the menu of the emulator itself appears(

**Comment by antangelo** [comment] 2024-08-04 23:20
Duplicate of #1270

**Closed as not planned by antangelo** 2024-08-04 23:20 UTC
Labels: enhancement
