### ISSUE TITLE
xemu (early xqemu) not work on Intel HD GT1

### ISSUE THREAD

**Issue by AD010** [xemu-project/xemu#235] opened 2021-03-06 11:17 UTC
i have this problem on all and latest version, Intel HD GT1, Windows 10 x64 (full hardware support OpenGL 1.0-4.3, latest drivers, software, runtime components etc), work only with wrapper mesa opengl32.dll, but fps is very slower. Need native work without this wrapper :

audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
nv2a: shader linking failed: Type mismatch: Type of _O;v_vtx;inv_w different between shaders.
Type mismatch: Type of _O;v_vtx;D0 different between shaders.
Type mismatch: Type of _O;v_vtx;D1 different between shaders.
Type mismatch: Type of _O;v_vtx;B0 different between shaders.
Type mismatch: Type of _O;v_vtx;B1 different between shaders.
Type mismatch: Type of _O;v_vtx;Fog different between shaders.
Type mismatch: Type of _O;v_vtx;T0 different between shaders.
Type mismatch: Type of _O;v_vtx;T1 different between shaders.
Type mismatch: Type of _O;v_vtx;T2 different between shaders.
Type mismatch: Type of _O;v_vtx;T3 different between shaders.

**Comment by thrimbor** [comment] 2021-03-06 12:52
Looks like a duplicate of #84.

**Closed as completed** 2021-03-06 22:54 UTC
