### ISSUE TITLE
Apply Widescreen Hacks from a database

### ISSUE THREAD

**Issue by rrrcabral** [xemu-project/xemu#518] opened 2021-10-31 22:03 UTC
### Feature Request

PCSX2 (ps2 emulator) has a .zip of known widescreen hacks in his installation, and every version add new hacks known.

Xemu(the author) can collect hacks from here:
https://assemblergames.org/viewtopic.php?t=60240
and here:
http://ps2wide.net/xbox.html
or other sources you know,
and store in a zip/folder that comes with installation.

then when anyone choose "use widescreen hacks" and set 16:9 screen in options(like PCSX2), xemu apply automatic if the game is on the collected hacks so far.

**Comment by Spidy123222** [comment] 2021-11-01 00:26
> ### Feature Request
> 
> PCSX2 (ps2 emulator) has a .zip of known widescreen hacks in his installation, and every version add new hacks known.
> 
> 
> 
> Xemu(the author) can collect hacks from here:
> 
> https://assemblergames.org/viewtopic.php?t=60240
> 
> and here:
> 
> http://ps2wide.net/xbox.html
> 
> or other sources you know,
> 
> and store in a zip/folder that comes with installation.
> 
> 
> 
> then when anyone choose "use widescreen hacks" and set 16:9 screen in options(like PCSX2), xemu apply automatic if the game is on the collected hacks so far.
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

This would be nice but having widescreen hacks toggle is possible but you would need a way to apply hacks. Atm there is no such system unless you use cheat engine (beware of anti cheat software for games they look if it's installed if you try to use it). He other way is to just patch the game files.

From what I know, This isn't in the current scope for xemu judging by last time someone asked. I'm pretty sure people are welcome to make a or for it some day though.

**Comment by dracc** [comment] 2021-11-01 11:42
Are you going to suggest widescreen hacks daily from now on?
Your feature request yesterday mentioned widescreen hacks too, which was closed with an explanation from mborgerson on why it won't happen.

**Comment by antangelo** [comment] 2023-10-16 20:52
Closing as duplicate of #517

**Closed as not planned by antangelo** 2023-10-16 20:52 UTC
Labels: enhancement
