### ISSUE TITLE
Ejecting disks during FMV Causes an assertion

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#516] opened 2021-10-31 00:51 UTC
### Bug Description

When ever you eject a disk while the intro FVM playing an assertion crashes the emulator:
Assertion failed: in_pitch >= in_width * 2, file /xemu/hw/xbox/nv2a/pgraph.c, line 4541
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L4541
Steps to reproduce this issue:
1.Insert a disk
2.Play FMV
3.Eject disk

### Expected Behavior

0.6.1-29-gc1e4e87f5f

### xemu Version

It should send you to the dashboard.

### System Information

OS: Ubuntu 20.04.3 LTS
CPU: Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
GPU: Mesa Intel(R) HD Graphics (BDW GT1)
GPU Drivers: 4.6 (Core Profile) Mesa 21.0.3

**Comment by mborgerson** [comment] 2021-10-31 01:20
Duplicate of #255

**Closed as completed by mborgerson** 2021-10-31 01:20 UTC
Labels: bug
