### ISSUE TITLE
Rendering through walls, affects multiple / many games

### ISSUE THREAD

**Issue by svensvond** [xemu-project/xemu#1437] opened 2023-05-18 19:48 UTC
### Title

At least these games are affected to this bug:

[007: From Russia with Love](https://xemu.app/titles/45410079/#007-From-Russia-with-Love) (Light source) https://github.com/xemu-project/xemu/issues/1009

 [Breakdown](https://xemu.app/titles/4e4d0009/#Breakdown) [(Example)](https://youtu.be/BOFl7Cuu47M?t=71)

 [Catwoman](https://xemu.app/titles/4541005c/)

 [Chicago Enforcer](https://xemu.app/titles/4b420005/#Chicago-Enforcer) (Gun)
xemu-2022-06-01-20-07-08

 [Driv3r](https://xemu.app/titles/49470038/#Driv3r) https://github.com/xemu-project/xemu/issues/891

 [Driver: Parallel Lines](https://xemu.app/titles/4947007f/#Driver-Parallel-Lines) (Objects)
xemu-2022-06-24-16-35-11

 [Far Cry Instincts](https://xemu.app/titles/55530008/#Far-Cry-Instincts) https://github.com/xemu-project/xemu/issues/458

 [IndyCar Series](https://xemu.app/titles/434d0006/#IndyCar-Series)
xemu-2022-07-26-11-38-36

 [IndyCar Series 2005](https://xemu.app/titles/434d0024/#IndyCar-Series-2005)
xemu-2022-07-26-11-48-49-min

 [Knight's Apprentice: Memorick's Adventures](https://xemu.app/titles/4d490004/#Knight-s-Apprentice-Memorick-s-Adventures) (Amd and Intel) (Skybox) https://github.com/xemu-project/xemu/issues/655

 [Juiced](https://xemu.app/titles/545100ef/#Juiced) (Objects)
xemu-2022-06-02-20-32-23

 [Marvel Nemesis: Rise of the Imperfects](https://xemu.app/titles/45410089/#Marvel-Nemesis-Rise-of-the-Imperfects)
xemu-2022-08-09-20-02-49

 [Miami Vice](https://xemu.app/titles/44580001/#Miami-Vice) (Objects)

 [Midtown Madness 3](https://xemu.app/titles/4d53002a/#Midtown-Madness-3)
xemu-2022-08-09-20-25-43

 [Oddworld: Munch's Oddysee](https://xemu.app/titles/4d530001/#Oddworld-Munch-s-Oddysee) (Skybox)

 [Peter Jackson's King Kong: The Official Game of the Movie](https://xemu.app/titles/5553004c/#Peter-Jackson-s-King-Kong-The-Official-Game-of-the-Movie) (Skybox)
xemu-2022-06-02-19-00-54

 Project Gotham Racing](https://xemu.app/titles/4d530003/#Project-Gotham-Racing)
xemu-2022-08-19-20-08-40

 [Quantum Redshift](https://xemu.app/titles/4d530015/#Quantum-Redshift-Chou-Kousoku-Kuukan-Battle-Race)

 [Tom Clancy's Splinter Cell](https://xemu.app/titles/5553000c/#Tom-Clancy-s-Splinter-Cell) (https://github.com/xemu-project/xemu/issues/804) (Objects)

 [Splinter Cell Pandora Tomorrow](https://xemu.app/titles/55530019/#Tom-Clancy-s-Splinter-Cell-Pandora-Tomorrow) (https://github.com/xemu-project/xemu/issues/823)

 [Tron 2.0: Killer App](https://xemu.app/titles/42560001/#Tron-2-0-Killer-App) (Disk)

 [Tom Clancy's Ghost Recon: Advanced Warfighter](https://xemu.app/titles/55530054/#Tom-Clancy-s-Ghost-Recon-Advanced-Warfighter) (Objects)

 [Serious sam](https://xemu.app/titles/54540004#Serious-Sam) (Objects)https://github.com/xemu-project/xemu/issues/802

 Syberia

 [V-Rally 3](https://xemu.app/titles/49470034/#V-Rally-3) https://github.com/xemu-project/xemu/issues/887

### Bug Description

Objects can be seen throw walls - which renders affected games quiet unplayable.
This bug has been in xemu for quiet some time, since ever from my perspective.
It was also reported in #1071 #1016

Tom Clancys Ghotst Recon Advanced Warfare

![xi4Eoke38G](https://github.com/xemu-project/xemu/assets/37634123/252ed519-9568-47a4-aae7-797b4cdde760)

### Expected Behavior

objects cant be seen through walls

### xemu Version

up to latest 0.79

### Additional Context

Seems to me a more heavy bug, looking at the amount of games and weight of this one.

**Comment by mborgerson** [comment] 2023-07-25 03:01
Apparent duplicate of #1016

**Closed as duplicate by mborgerson** 2023-07-25 03:01 UTC
Labels: bug
