### ISSUE TITLE
FIX MACOS VERSION (UNIVERSAL)

### ISSUE THREAD

**Issue by Juandelospalote** [xemu-project/xemu#1571] opened 2023-12-17 20:58 UTC
### Bug Description

The universal binary doesn't work properly on MacOS big sur 11, my macbook pro is late 2017 model A1706 and xemu shows a lot of bugs (sound problems, bad graphics, some games like Capcom Vs SNK 2 EO shows only the 3D polygons withow textures, some others games doesn't even boot) and many more...

Please fix the problems because on windows those never happens...

### Expected Behavior

The emulator should boot and works properly...

### xemu Version

Version 0.7.117 (Nov 19, 2023)

### System Information

OS: MacOS Big Sur 11.2.3
Model: A1706
GPU: Intel Iris Plus Graphics 650 1536 MB
RAM: 16 gb

**Comment by antangelo** [comment] 2023-12-17 21:12
Partial duplicate of #632 . The other issues are not actionable without more information.

**Closed as not planned by antangelo** 2023-12-17 21:12 UTC
Labels: bug
