### ISSUE TITLE
Re: The Punisher

### ISSUE THREAD

**Issue by TheChosenOne914** [xemu-project/xemu#1421] opened 2023-04-15 19:16 UTC
### Bug Description

the punisher i keep getting this c++ error at random times happens when i start the xemu app or certain levels clicking on abort retry ignore all do the same either crashes xemu app forcing it to close or lock up and freeze up not responding Microsoft Visual C++ Runtime Library Assertion Failed! Program File: /hw/xbox/nv2a/pfifo.c Line: 297 Expression false for information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts (Press Retry to debug the application - jit must be enabled)

### Expected Behavior

the punisher i keep getting this c++ error at random times happens when i start the xemu app or certain levels clicking on abort retry ignore all do the same either crashes xemu app forcing it to close or lock up and freeze up not responding Microsoft Visual C++ Runtime Library Assertion Failed! Program File: /hw/xbox/nv2a/pfifo.c Line: 297 Expression false for information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts (Press Retry to debug the application - jit must be enabled)

### xemu Version

0.7.86 is the version iam having issues on with this game

### System Information

OS: Windows 11 pro
CPU: Intel I7 13th Gen 13700K
GPU: Nvidia RTX 4070 TI Ventus 3X 12GB

**Comment by snooproxy** [comment] 2024-08-04 17:46
happening for me too. still waiting for answers.
although I am getting a few more errors from the same file at different line numbers.
being 297, 424 and 304

**Comment by antangelo** [comment] 2024-08-05 04:34
Duplicate of #310

**Closed as not planned by antangelo** 2024-08-05 04:34 UTC
Labels: bug
