### ISSUE TITLE
Dino Crisis 3 certain runtime error crash if playing on full screen 

### ISSUE THREAD

**Issue by jimkage** [xemu-project/xemu#1629] opened 2024-04-01 21:13 UTC
### Bug Description

Keep getting error messagers like these
<img width="308" alt="Screenshot_1" src="https://github.com/xemu-project/xemu/assets/78828042/8769c76c-d322-413a-a1c9-f077cff2e203">

### Expected Behavior

Should not happen

### xemu Version

 0.7.120

### System Information

OS: Windows 10
CPU: i7-6700k 4.OOGHz
GPU: NVIDIA GTX 1070
GPU Driver 551.86

### Additional Context

Can play in windowed mode and just press ignore twice and keep on playing without the emulator crashing.

**Comment by antangelo** [comment] 2024-04-01 21:22
Duplicate of #1227

**Closed as completed by antangelo** 2024-04-01 21:22 UTC
Labels: bug
