### ISSUE TITLE
Xemu lagging on mac

### ISSUE THREAD

**Issue by Squidwardisiconic** [xemu-project/xemu#957] opened 2022-05-23 20:04 UTC
### Bug Description

For some reason, every time i boot up xemu for the startup animation its been lagging pretty bad like 25 frames and its so weird because the emulator used to work pretty good also games will have these stutters and lags and i dont know whats up with that. If i can get some help with this that would be great
<img width="1011" alt="Screen Shot 2022-05-23 at 4 02 14 PM" src="https://user-images.githubusercontent.com/93882385/169897140-8722af07-2c4f-4931-9316-bc359940e305.png">

### Expected Behavior

I hope that it will stop lagging

### xemu Version

I tried xemu 0.7.17 but that had a problem so i downgraded and it still has the same problem as i just described

### System Information

Mac M1 chip
8gb memory

**Comment by abaire** [comment] 2022-05-23 20:12
"so i downgraded and it still has the same problem as i just described"

This seems like a pretty clear indication that the problem is the machine and not xemu, your best bet is to search the internet for ideas on optimizing OpenGL applications on M1. 

Apple does not seem to put much effort into their OpenGL drivers anymore and their GL-on-Metal implementation for M1 seems to be in flux still. You may be best off just being patient and hoping they happen to fix it or looking to see if there's any way to provide feedback to Apple.

In any case, GitHub is not the right place to make support requests. You can ask on Discord to see if anybody else can confirm the behavior on other M1s (you should also specify the actual chip there since M1 covers a range with very different capabilities).

**Comment by mborgerson** [comment] 2022-05-23 20:14
Thanks for reporting. I've tested on my M1 mac mini and it matches performance described here. xemu is evolving and performance is expected to change as it evolves (sometimes it will be worse, sometimes better). I'll close this because the issue does not describe a specific issue and performance is still acceptable (enough) in this case.

**Closed as completed by mborgerson** 2022-05-23 20:14 UTC
Labels: bug
