### ISSUE TITLE
Xemu error for Visual C++runtime library

### ISSUE THREAD

**Issue by Gareth17andMinnie14** [xemu-project/xemu#1487] opened 2023-07-19 19:57 UTC
### Bug Description

I just found this error for Xemu emulator if you leave it idle for a few minutes you get a popup error telling you about the issue with Xemu visual c++ 
![Xemu Visual C++ Error](https://github.com/xemu-project/xemu/assets/122693175/11a7ae1a-4063-429c-88e7-427ba1e15e43)

### Expected Behavior

Only has an error popup if you leave Xemu idle for a few minutes.

### xemu Version

Version: 0.7.99
Branch:   master
Commit:  158cc0d14001450c082e17ffd8cd407ac795525e
Date: Mon Jul 17 11:14:03 UTC 2023

### System Information

CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
OS Platform: Windows
OS Version: 22H2
Manufacturer: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver: 4.0.0 NVIDIA 536.67
Shader: 4.00 NVIDIA via Cg compiler

### Additional Context

MCPX Boot ROM MD5 Hash: d49c52a4102f6df7bcf8d0617ac475ed
Flash ROM (BIOS) MD5 Hash: e8dd61cc6abdbd06aac185e371312dc1

**Comment by dracc** [comment] 2023-07-19 20:13
Duplicate of #310.

Edit: This is the second time you post this duplicated issue. Please stop spamming.

**Closed as completed** 2023-07-19 20:26 UTC
Labels: bug
