### ISSUE TITLE
XEMU crashes on launch if no audio device detected - SDL_OpenAudioDevice failed

### ISSUE THREAD

**Issue by iamstizzle** [xemu-project/xemu#478] opened 2021-10-07 00:30 UTC
### Bug Description

To reproduce:

1 On Windows 10 with no speakers or audio devices plugged in.
2.  Launch xemu.exe

The application briefly opens and then immediately closes.
The last line of the xemu.log shows:
**SDL_OpenAudioDevice failed**

### Expected Behavior

I would expect the application not close unexpectedly even when no audio devices are detected.

### xemu Version

xemu_version: 0.6.1-9-g631c818c1e
xemu_branch: master
xemu_commit: 631c818c1ecbf2c7f34a574816cc9f80db8670af
xemu_date: Mon Sep 27 20:21:29 UTC 2021

### System Information

OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz   2.50 GHz
GPU: --
GL_RENDERER: GeForce GTX 1660 Ti/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 461.37
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler

### Additional Context

On the pc I'm using for xemu, I only have my bluetooth headset as an audio device.

If the bluetooth headset is off when xemu launches. Xemu will immediately close.
The last line of the xemu.log shows:
**SDL_OpenAudioDevice failed**

If I turn on my bluetooth headset. no issues are encountered when launching xemu.

**Comment by mborgerson** [comment] 2021-10-07 00:35
Thanks for reporting. This is a duplicate of #354, so I'll close this one.

**Closed as duplicate by mborgerson** 2021-10-07 00:35 UTC
Labels: bug
