### ISSUE TITLE
https://xemu.app/titles/4d530004/#Halo-Combat-Evolved

### ISSUE THREAD

**Issue by Gareth17andMinnie14** [xemu-project/xemu#1339] opened 2023-01-14 18:48 UTC
### Title

https://xemu.app/titles/4d530004/#Halo-Combat-Evolved

MS-004 [4d530004]

### Bug Description

![Evidence](https://user-images.githubusercontent.com/122693175/212490337-619cdd0b-dd5b-45ef-a977-06674bec9917.PNG)
![Evidence 2](https://user-images.githubusercontent.com/122693175/212490354-fa35cd1a-db03-4c84-a8f6-9b6417d670e3.PNG)

It seems to be the text in the game when trying to turn up the resolution from 1x to 4x and lastly 10x you somehow get a really strange lines around the letters making it really strange and making it hard for the game and I also found this issue to be really a problem to make the game less fun, so this problem needs to be sorted out because it seems to be really annoying.

### Expected Behavior

When playing the campaign and your about to wake up from sleeping in the cryo tube, basically there is some sort of pixel bug that during the black boarders and disappears after the black boarders slide away to continue the campaign to start playing the game which is really annoying and a problem for this game and other games too.
![xemu-2023-01-14-18-12-22](https://user-images.githubusercontent.com/122693175/212490743-1f023f2d-b028-4df7-a9d3-0f670e231382.png)

### xemu Version

All versions, tested on Version: 0.7.76

Branch: master

 Date: Jan 14th 2023

### System Information

CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver:  4.0.0 NVIDIA 528.02
Shader:  4.00 NVIDIA via Cg compiler

### Additional Context

No any type of additional information or log output to report.

**Comment by Triticum0** [comment] 2023-01-18 15:21
Dupe of https://github.com/xemu-project/xemu/issues/57

**Closed as completed** 2023-01-18 15:47 UTC
Labels: bug
