### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by upriver4** [xemu-project/xemu#1630] opened 2024-04-02 00:22 UTC
### Feature Request

Can you verify Xemu so people who discover it through Flathub know it's official?

### Alternatives

Xemu can be verified by putting a token on the website or by verifying the GitHub

### Additional Context

Here's a link to the documentation from Flathub https://docs.flathub.org/docs/for-app-authors/verification

**Comment by mborgerson** [comment] 2024-04-02 09:13
Will do. Closed as duplicate of https://github.com/flathub/app.xemu.xemu/issues/152

**Closed as completed by mborgerson** 2024-04-02 09:13 UTC
Labels: enhancement
